# Generated by Django 5.1 on 2025-03-11 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetup',
            name='image',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
